version: '3.8'


services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    netoworks:
      - frontend
      - backend


  app1:
    build:
      context:
    expose:
      - "5000"
    networks:
      - backend


  app2:
    build:
      context:
    expose:
      - "5001"
    networks:
      - backend


networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
